/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import static Main.Analizador.Op_Insert;

/**
 *
 * @author kilroy
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        I_consulta = new javax.swing.JTextField();
        btn_analizar = new javax.swing.JButton();
        bnt_limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 210, 194));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sql.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 150));

        I_consulta.setBackground(new java.awt.Color(102, 102, 102));
        I_consulta.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 14)); // NOI18N
        I_consulta.setForeground(new java.awt.Color(51, 255, 0));
        I_consulta.setCaretColor(new java.awt.Color(0, 153, 0));
        I_consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        I_consulta.setSelectedTextColor(new java.awt.Color(0, 204, 0));
        I_consulta.setSelectionColor(new java.awt.Color(0, 153, 0));
        getContentPane().add(I_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 493, 44));

        btn_analizar.setText("Analizar");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        bnt_limpiar.setText("Limpiar");
        bnt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 430));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
      String cadena;
      StringTokenizer st = new StringTokenizer(I_consulta.getText());
      
      cadena = st.nextToken();
      cadena = cadena.toUpperCase();
      if(cadena.equals("INSERT")||cadena.equals("DELETE")|| cadena.equals("UPDATE")||cadena.equals("CREATE")||cadena.equals("SELECT")){
          if(cadena.equals("INSERT")){
            Op_Insert(I_consulta.getText());  
          }
          else if(cadena.equals("DELETE")){
              
          }
          else if(cadena.equals("UPDATE")){
          
          }
          else if(cadena.equals("CREATE")){
          
          }
          else if(cadena.equals("SELECT")){
          
          }
      }
      else{
          JOptionPane.showMessageDialog(null, cadena+" No es una Expresion valida");
      }
      
    }//GEN-LAST:event_btn_analizarActionPerformed

    private void bnt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_limpiarActionPerformed
        I_consulta.setText(null);
        I_consulta.requestFocus();
    }//GEN-LAST:event_bnt_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField I_consulta;
    private javax.swing.JButton bnt_limpiar;
    private javax.swing.JButton btn_analizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
